#!/bin/sh
#
# test for wakati with "wo"
#
# $Id: kakasi-11,v 1.2 2017-01-12 07:26:21 knok Exp $

LOG=`pwd`/test-log
echo '  *** starting ' $0 >> $LOG

. ./env.sh

INPUT=./data/korewo-in.txt
TMPOUT=./data/tmpout.txt
EXPECT=./data/korewo-out.txt

clean() {
    rm -f $TMPOUT
}

../src/kakasi -w -iutf8 -outf8 < $INPUT | tr -d '\015' > $TMPOUT
if cmp -s $TMPOUT $EXPECT
then
    echo "test passed." >> $LOG
else
    echo "test failed. the output was:" >> $LOG
    cat $TMPOUT >> $LOG
    clean
    exit 1
fi

clean

exit 0
